a=input("enter the name:")
b=input("enter the age:")
c=input("enter the qualifications:")
d=input("enter the name of parents/n:")
e=input("enter the college name:")
f=input("enter the % of 10th mark:")
g=input("enter the % of 12th:")
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)